jobs:
  node-version:
      runs-on: ubuntu-latest
      steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@vq
        with:
          node-version: 6
      - name: Log node version
        run: node -v 
